targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/core/presentation/pages/**/**_page.dart
      injectable_generator:injectable_builder:
        generate_for:
          - lib/core/dependency_injection.dart
          - lib/core/infrastructure/**/**_impl.dart
      freezed:
        generate_for:
          - lib/core/domain/entity/**.dart
          - lib/core/application/**/**_state.dart
          - lib/core/application/**/**_bloc.dart   
